# render.yaml (at your repo root)

services:
  # ───────────────────────────
  # Backend API (Express/Mongo)
  # ───────────────────────────
  - type: web
    name: gisconnect-api
    runtime: node
    region: oregon
    plan: starter
    branch: main
    rootDir: server
    buildCommand: npm ci
    startCommand: node index.js
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: CORS_ORIGINS
        value: https://gisconnect.onrender.com,http://localhost:5173
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_URL_TTL_SECONDS
        value: "900"

  # ───────────────────────────
  # Frontend (Vite static site)
  # ───────────────────────────
  - type: web
    name: gisconnect-web
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: client/gisconnect
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_BASE
        # During first-time Blueprint creation, type the API URL Render gives to gisconnect-api.
        # After the API deploys, you can update this to the final https://<api>.onrender.com
        value: https://gisconnect-api.onrender.com
